# configuration file for demo
pretrained: ./wandb/run-20240821_071347-ocaaf1o2/files/model.pth
data_root: /data/public/kitti
top_k : 5

# ----- base config
eval: True
num_workers: 4
batch_size: 1
device: cuda # device to use for training / testing 

# ----- data config
data_name: kittidb

grd_img_size: [256, 1024]
arl_img_size: [512, 512]
arl_zoom_ratio: 1


# ----- model config
mask: False
num_multimask_outputs: 64

patch_size: 32
mlp_ratio: 4
qkv_bias: True

num_heads: 6 # Number of attention heads inside the transformer's attentions
num_enc_layers: 12 # Number of encoding layers in the transformer

dim_embed: 384 # Size of the embeddings (dimension of the transformer)
dim_feature: 1000

repeat_grd_factor: 3
grd_to_arl_factor: 4 # 360 / cam_fov