version: "3.8"

services:
  transgeo:
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        USERNAME: $USER
    stdin_open: true
    tty: true
    ipc: host
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
    volumes:
      - ../:/workspace/
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /workspace/
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]