# configuration file for training
# ----- base config
infer: False
resume: False

seed: 42
num_workers: 8

batch_size: 8 # 12

retr_only: False
device: cuda # device to use for training / testing 

ckpt_dir: ../ckpts
epochs: 50
start_epoch: 1

# ----- data config
data_name: kitti
data_root: /storage2/public/kitti    

grd_img_size: [128, 512]
arl_img_size: [320, 320]

shift_range_lat: 20 
shift_range_lon: 20 
rotation_range: 10 
fov: 0

arl_zoom_ratio: 2.0

# kitti only
# train_pt_list: ./datasets/splits/kitti/test1_mini.txt
# val_pt_list: ./datasets/splits/kitti/test1_mini.txt

train_pt_list: ./datasets/splits/kitti/train_files.txt
val_pt_list: ./datasets/splits/kitti/test1_files.txt

# ----- optimizer config
lr: 0.0001
weight_decay: 0.03

optimizer: sam
cos: True

# ----- model config
patch_size: 16
mlp_ratio: 4
qkv_bias: True

num_heads: 6 # Number of attention heads inside the transformer's attentions
num_enc_layers: 12 # Number of encoding layers in the transformer
num_dec_layers: 6

dim_embed: 384 # Size of the embeddings (dimension of the transformer)
dim_embed_2: 192
dim_feature: 1000

dim_feedforward: 2048 # Intermediate size of the feedforward layers in the transformer blocks  
dropout: 0.1 # Dropout applied in the transformer
pre_norm: False

num_queries: 64 # Number of query slots

set_cost_class: 1 # Class coefficient in the matching cost
set_cost_bbox: 5 # L1 box coefficient in the matching cost

label_loss_coef: 1
bbox_loss_coef: 0.1

eos_coef: 0.1 # Relative classification weight of the no-object class