# configuration file for training
infer: False

resume: False

seed: 42
num_workers: 8

batch_size: 32

task: RETR # RETR / LOCAL 
device: cuda # device to use for training / testing 

train:

  ckpt_dir: ../ckpts
  epochs: 150
  start_epoch: 1

  lr: 0.0001
  weight_decay: 0.03  
  lr_drop: 200
  clip_max_norm: 0.1 # gradient clipping max norm

  optimizer: adamw

dataset:
  
  data_name: cvusa
  data_root: /storage2/public/cvusa/  
  fov: 0

  grnd_img_size: [112, 616] # [112, 616]
  arl_img_size: [256, 256]

  train_pt_list: ./datasets/splits/cvusa/train-19zl.csv
  val_pt_list: ./datasets/splits/cvusa/val-19zl.csv
  
model:

  grnd_img_size: [112, 616] # [112, 616]
  arl_img_size: [256, 256]

  patch_size: 16
  
  mlp_ratio: 4
  qkv_bias: True

  num_heads: 6 # Number of attention heads inside the transformer's attentions
  num_enc_layers: 12 # Number of encoding layers in the transformer

  dim_embed: 384 # Size of the embeddings (dimension of the transformer)
  dim_feature: 1000