# configuration file for training
# ----- base config
infer: False
resume: ./wandb/run-20231108_152418-o9oi42m3/files/epoch_10.pth

seed: 42
num_workers: 8

batch_size: 8 # 12

retr_only: False
device: cuda # device to use for training / testing 

ckpt_dir: ../ckpts
epochs: 50
start_epoch: 1

# ----- data config
data_name: ford
data_root: /storage2/public/ford    

grd_img_size: [256, 1024]
arl_img_size: [512, 512]

shift_range_lat: 20 
shift_range_lon: 20 
rotation_range: 180 

whole: 0

# ----- optimizer config
lr: 0.0001
weight_decay: 0.03

optimizer: adamw
cos: True

# ----- model config
retr_only: False
rng_mask: True

num_queries: 100

patch_size: 32
mlp_ratio: 4
qkv_bias: True

num_heads: 6 # Number of attention heads inside the transformer's attentions
num_enc_layers: 12 # Number of encoding layers in the transformer

dim_embed: 384 # Size of the embeddings (dimension of the transformer)
dim_feature: 1000

repeat_grd_factor: 3
grd_to_arl_factor: 4 # 360 / cam_fov

set_cost_class: 1 # Class coefficient in the matching cost
set_cost_bbox: 5 # L1 box coefficient in the matching cost

label_loss_coef: 1
bbox_loss_coef: 5

eos_coef: 0.01 # Relative classification weight of the no-object class