# configuration file for training
# ----- base config
infer: False
resume: False

seed: 42
num_workers: 8

batch_size: 1 #12

task: RETR # RETR / POSE 
device: cuda # device to use for training / testing 

ckpt_dir: ../ckpts
epochs: 50
start_epoch: 1

# ----- optimizer config
lr: 0.00005
weight_decay: 0.03

optimizer: sam
cos: True

# ----- data config
data_name: vigor
data_root: /storage2/public/vigor/    

grd_img_size: [320, 640] 
arl_img_size: [320, 320]

shift_range_lat: 0 
shift_range_lon: 0 
rotation_range: 0 
fov: 0

same_area: True

# ----- model config
patch_size: 16
mlp_ratio: 4
qkv_bias: True

num_heads: 6 # Number of attention heads inside the transformer's attentions
num_enc_layers: 12 # Number of encoding layers in the transformer

dim_embed: 384 # Size of the embeddings (dimension of the transformer)
dim_feature: 1000