# configuration file for training
# ----- base config
eval: False
resume: False

seed: 42
num_workers: 8

batch_size: 16 

device: cuda # device to use for training / testing 

epochs: 50
start_epoch: 1

# ----- data config
data_name: vigor
data_root: /data/public/VIGOR    

grd_img_size: [320, 640] 
arl_img_size: [320, 320]

same_area: False
fov: 0

# ----- optimizer config
lr: 0.00001
weight_decay: 0.001

optimizer: adamw
cos: True

# ----- model config
num_queries: 128

patch_size: 16
mlp_ratio: 4
qkv_bias: True

num_heads: 6 # Number of attention heads inside the transformer's attentions
num_enc_layers: 12 # Number of encoding layers in the transformer

dim_embed: 384 # Size of the embeddings (dimension of the transformer)
dim_feature: 1000

repeat_grd_factor: 3
grd_to_arl_factor: 1 # 360 / cam_fov

# ----- criterion config
set_cost_class: 1 # Class coefficient in the matching cost
set_cost_bbox: 5 # L1 box coefficient in the matching cost

label_loss_coef: 1
bbox_loss_coef: 5

eos_coef: 0.01 # Relative classification weight of the no-object class

